/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ActivateFactorRequest {
    /**
    * Required. Specifies the factor to be verified.
    */
    'deviceId'?: number;
    /**
    * Optional. Sets the window of time in seconds that the factor must be verified within. 
    */
    'expiresIn'?: number;
    /**
    * Optional. Only applies to Email MagicLink factor.
    */
    'redirectTo'?: string;
    /**
    * Optional. Only applies to SMS factor. A message template that will be sent via SMS.
    */
    'customMessage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deviceId",
            "baseName": "device_id",
            "type": "number"
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number"
        },
        {
            "name": "redirectTo",
            "baseName": "redirect_to",
            "type": "string"
        },
        {
            "name": "customMessage",
            "baseName": "custom_message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ActivateFactorRequest.attributeTypeMap;
    }
}

