/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AuthMethod } from './authMethod';

export class Connector {
    /**
    * The connectors unique ID in OneLogin.
    */
    'id'?: number;
    /**
    * The name of the connector.
    */
    'name'?: string;
    'authMethod'?: AuthMethod;
    /**
    * Indicates if apps created using this connector will be allowed to create custom parameters.
    */
    'allowsNewParameters'?: boolean;
    /**
    * A link to the apps icon url.
    */
    'iconUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "authMethod",
            "baseName": "auth_method",
            "type": "AuthMethod"
        },
        {
            "name": "allowsNewParameters",
            "baseName": "allows_new_parameters",
            "type": "boolean"
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Connector.attributeTypeMap;
    }
}

