/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Device {
    'deviceId'?: string;
    'userDisplayName'?: string;
    'typeDisplayName'?: string;
    'authFactorName'?: string;
    '_default'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deviceId",
            "baseName": "device_id",
            "type": "string"
        },
        {
            "name": "userDisplayName",
            "baseName": "user_display_name",
            "type": "string"
        },
        {
            "name": "typeDisplayName",
            "baseName": "type_display_name",
            "type": "string"
        },
        {
            "name": "authFactorName",
            "baseName": "auth_factor_name",
            "type": "string"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Device.attributeTypeMap;
    }
}

