/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Array of factor specific properties. For example, the token or totp code for OneLogin Protect.
*/
export class FactorInnerFactorData {
    /**
    * The token which can be used to verify the factor registration.
    */
    'verificationToken'?: string;
    /**
    * OTP Url that can be leveraged for any authenticator that supports the key uri format.
    */
    'totpUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "verificationToken",
            "baseName": "verification_token",
            "type": "string"
        },
        {
            "name": "totpUrl",
            "baseName": "totp_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FactorInnerFactorData.attributeTypeMap;
    }
}

