/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GenerateMfaTokenRequest {
    /**
    * Set the duration of the token in seconds.
    */
    'expiresIn'?: string;
    /**
    * Defines if the token is reusable multiple times within the expiry window.
    */
    'reusable'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "string"
        },
        {
            "name": "reusable",
            "baseName": "reusable",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GenerateMfaTokenRequest.attributeTypeMap;
    }
}

