/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GenerateMfaToken200Response {
    /**
    * Token can function as a temporary MFA token. It can be used to authenticate for any app when valid.
    */
    'mfaToken'?: string;
    /**
    * true indcates the token can be used multiple times. false indicates the token is invalid after a single use
    */
    'reusable'?: boolean;
    /**
    * Defines the expiration time and date for the token. Format is UTC time.
    */
    'expiresAt'?: string;
    /**
    * Defines the expiration time and date for the token. Format is UTC time.
    */
    'deviceId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mfaToken",
            "baseName": "mfa_token",
            "type": "string"
        },
        {
            "name": "reusable",
            "baseName": "reusable",
            "type": "boolean"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string"
        },
        {
            "name": "deviceId",
            "baseName": "device_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GenerateMfaToken200Response.attributeTypeMap;
    }
}

