/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetAvailableFactors200ResponseInner {
    /**
    * Identifier for the factor which will be used for user enrollment
    */
    'factorId'?: number;
    /**
    * Authentication factor name, as it appears to administrators in OneLogin.
    */
    'name'?: string;
    /**
    * Internal use only
    */
    'authFactorName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "factorId",
            "baseName": "factor_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "authFactorName",
            "baseName": "auth_factor_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetAvailableFactors200ResponseInner.attributeTypeMap;
    }
}

