/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetRiskScore200Response {
    /**
    * A risk score 0 is low risk and 100 is the highest risk level possible.
    */
    'score'?: number;
    /**
    * Triggers are indicators of some of the key items that influenced the risk score.
    */
    'triggers'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        },
        {
            "name": "triggers",
            "baseName": "triggers",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return GetRiskScore200Response.attributeTypeMap;
    }
}

