/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetRateLimit200ResponseData } from './getRateLimit200ResponseData';
import { Status } from './status';

export class GetRateLimit200Response {
    'status'?: Status;
    'data'?: GetRateLimit200ResponseData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "Status"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetRateLimit200ResponseData"
        }    ];

    static getAttributeTypeMap() {
        return GetRateLimit200Response.attributeTypeMap;
    }
}

