/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetScoreInsights200ResponseScores } from './getScoreInsights200ResponseScores';

export class GetScoreInsights200Response {
    'scores'?: GetScoreInsights200ResponseScores;
    'total'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scores",
            "baseName": "scores",
            "type": "GetScoreInsights200ResponseScores"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetScoreInsights200Response.attributeTypeMap;
    }
}

