/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetScoreInsights200ResponseScores {
    'minimal'?: number;
    'low'?: number;
    'medium'?: number;
    'high'?: number;
    'veryHigh'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minimal",
            "baseName": "minimal",
            "type": "number"
        },
        {
            "name": "low",
            "baseName": "low",
            "type": "number"
        },
        {
            "name": "medium",
            "baseName": "medium",
            "type": "number"
        },
        {
            "name": "high",
            "baseName": "high",
            "type": "number"
        },
        {
            "name": "veryHigh",
            "baseName": "very_high",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetScoreInsights200ResponseScores.attributeTypeMap;
    }
}

