/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetUserApps200ResponseInner {
    /**
    * The App ID
    */
    'id'?: number;
    /**
    * A url for the icon that represents the app in the OneLogin portal
    */
    'iconUrl'?: string;
    /**
    * Boolean that indicates if the OneLogin browser extension is required to launch this app.
    */
    'extension'?: boolean;
    /**
    * Unqiue identifier for this user and app combination.
    */
    'loginId'?: number;
    /**
    * The name of the app.
    */
    'name'?: string;
    'provisioningStatus'?: GetUserApps200ResponseInner.ProvisioningStatusEnum;
    /**
    * If provisioning is enabled this indicates the state of provisioning for the given user.
    */
    'provisioningState'?: GetUserApps200ResponseInner.ProvisioningStateEnum;
    /**
    * Indicates if provisioning is enabled for this app.
    */
    'provisioningEnabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string"
        },
        {
            "name": "extension",
            "baseName": "extension",
            "type": "boolean"
        },
        {
            "name": "loginId",
            "baseName": "login_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "provisioningStatus",
            "baseName": "provisioning_status",
            "type": "GetUserApps200ResponseInner.ProvisioningStatusEnum"
        },
        {
            "name": "provisioningState",
            "baseName": "provisioning_state",
            "type": "GetUserApps200ResponseInner.ProvisioningStateEnum"
        },
        {
            "name": "provisioningEnabled",
            "baseName": "provisioning_enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GetUserApps200ResponseInner.attributeTypeMap;
    }
}

export namespace GetUserApps200ResponseInner {
    export enum ProvisioningStatusEnum {
        Enabling = <any> 'enabling',
        Disabling = <any> 'disabling',
        EnablingPendingApproval = <any> 'enabling_pending_approval',
        DisablingPenddingApproval = <any> 'disabling_pendding_approval',
        Enabled = <any> 'enabled',
        Disabled = <any> 'disabled',
        DisablingFailed = <any> 'disabling_failed',
        EnablingFailed = <any> 'enabling_failed'
    }
    export enum ProvisioningStateEnum {
        Unknown = <any> 'unknown',
        Provisioning = <any> 'provisioning',
        Modifying = <any> 'modifying',
        Deleting = <any> 'deleting',
        ProvisioningPendingApproval = <any> 'provisioning_pending_approval',
        DeletingPendingApproval = <any> 'deleting_pending_approval',
        ModifyingPendingApproval = <any> 'modifying_pending_approval',
        Linking = <any> 'linking',
        Provisioned = <any> 'provisioned',
        Deleted = <any> 'deleted',
        ModifyingFailed = <any> 'modifying_failed',
        ProvisioningFailed = <any> 'provisioning_failed',
        DeletingFailed = <any> 'deleting_failed',
        LinkingFailed = <any> 'linking_failed',
        Disabled = <any> 'disabled',
        Nonexistent = <any> 'nonexistent',
        ModifyingPendingApprovalThenDisabled = <any> 'modifying_pending_approval_then_disabled'
    }
}
