/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A set of attributes allow control over the information that is included in the hook context.
*/
export class HookOptions {
    'riskEnabled'?: boolean;
    'locationEnabled'?: boolean;
    'mfaDeviceInfoEnabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "riskEnabled",
            "baseName": "risk_enabled",
            "type": "boolean"
        },
        {
            "name": "locationEnabled",
            "baseName": "location_enabled",
            "type": "boolean"
        },
        {
            "name": "mfaDeviceInfoEnabled",
            "baseName": "mfa_device_info_enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return HookOptions.attributeTypeMap;
    }
}

