/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';


export class Schema3 {
    /**
    * Apps unique ID in OneLogin.
    */
    'id'?: number;
    /**
    * ID of the apps underlying connector.
    */
    'connectorId'?: number;
    /**
    * App name.
    */
    'name'?: string;
    /**
    * Freeform description of the app.
    */
    'description'?: string;
    /**
    * Indicates if the app is visible in the OneLogin portal.
    */
    'visible'?: boolean;
    /**
    * An ID indicating the type of app.
    */
    'authMethod'?: Schema3.AuthMethodEnum;
    
    'authMethodDescription'?: string
    /**
    * The date the app was created.
    */
    'createdAt'?: string;
    /**
    * The date the app was last updated.
    */
    'updatedAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "connectorId",
            "baseName": "connector_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean"
        },
        {
            "name": "authMethod",
            "baseName": "auth_method",
            "type": "Schema3.AuthMethodEnum"
        },
        {
            "name": "authMethodDescription",
            "baseName": "auth_method_description",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
    ];

    static getAttributeTypeMap() {
        return Schema3.attributeTypeMap;
    }
}

export namespace Schema3 {
    export enum AuthMethodEnum {
        NUMBER_0 = <any> 0,
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2,
        NUMBER_3 = <any> 3,
        NUMBER_4 = <any> 4,
        NUMBER_6 = <any> 6,
        NUMBER_7 = <any> 7,
        NUMBER_8 = <any> 8
    }
}
