/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class ListAccessTokenClaims200ResponseInner {
  "id"?: number;
  "label"?: string;
  "userAttributeMappings"?: string;
  "userAttributeMacros"?: string;
  "attributesTransformations"?: string;
  "skipIfBlank"?: boolean;
  "values"?: Array<string>;
  "defaultValues"?: string;
  "provisionedEntitlements"?: boolean;
  "name"?: string;
  "safeEntitlementsEnabled"?: string;
  "inherited"?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "safeEntitlementsEnabled",
      baseName: "safe_entitlements_enabled",
      type: "string",
    },
    {
      name: "inherited",
      baseName: "inherited",
      type: "boolean",
    },
    {
      name: "label",
      baseName: "label",
      type: "string",
    },
    {
      name: "userAttributeMappings",
      baseName: "user_attribute_mappings",
      type: "string",
    },
    {
      name: "userAttributeMacros",
      baseName: "user_attribute_macros",
      type: "string",
    },
    {
      name: "attributesTransformations",
      baseName: "attributes_transformations",
      type: "string",
    },
    {
      name: "skipIfBlank",
      baseName: "skip_if_blank",
      type: "boolean",
    },
    {
      name: "values",
      baseName: "values",
      type: "Array<string>",
    },
    {
      name: "defaultValues",
      baseName: "default_values",
      type: "string",
    },
    {
      name: "provisionedEntitlements",
      baseName: "provisioned_entitlements",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap() {
    return ListAccessTokenClaims200ResponseInner.attributeTypeMap;
  }
}
