/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListAuthorizationServers200ResponseInnerConfiguration } from './listAuthorizationServers200ResponseInnerConfiguration';

export class ListAuthorizationServers200ResponseInner {
    'id'?: number;
    'name'?: string;
    'configuration'?: ListAuthorizationServers200ResponseInnerConfiguration;
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "ListAuthorizationServers200ResponseInnerConfiguration"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListAuthorizationServers200ResponseInner.attributeTypeMap;
    }
}

