/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class MappingAction {
  /**
   * The action to apply
   */
  "action"?: string;
  /**
   * Only applicable to provisioned and set_* actions. Items in the array will be a plain text string or valid value for the selected action.
   */
  "value"?: Array<string>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "action",
      baseName: "action",
      type: "string",
    },
    {
      name: "value",
      baseName: "value",
      type: "Array<string>",
    },
  ];

  static getAttributeTypeMap() {
    return MappingAction.attributeTypeMap;
  }
}
