/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Source } from './source';

export class RiskRule {
    'id'?: string;
    /**
    * The name of this rule
    */
    'name'?: string;
    'description'?: string;
    /**
    * The type parameter specifies the type of rule that will be created.
    */
    'type'?: RiskRule.TypeEnum;
    /**
    * The target parameter that will be used when evaluating the rule against an incoming event.
    */
    'target'?: RiskRule.TargetEnum;
    /**
    * A list of IP addresses or country codes or names to evaluate against each event.
    */
    'filters'?: Array<string>;
    'source'?: Source;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RiskRule.TypeEnum"
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "RiskRule.TargetEnum"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<string>"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "Source"
        }    ];

    static getAttributeTypeMap() {
        return RiskRule.attributeTypeMap;
    }
}

export namespace RiskRule {
    export enum TypeEnum {
        Blacklist = <any> 'blacklist',
        Whitelist = <any> 'whitelist'
    }
    export enum TargetEnum {
        Ip = <any> 'location.ip',
        AddressCountryIsoCode = <any> 'location.address.country_iso_code'
    }
}
