/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An Object containing User details.
*/
export class RiskUser {
    /**
    * A unique identifier for the user.
    */
    'id': string;
    /**
    * A name for the user.
    */
    'name'?: string;
    /**
    * Indicates if the metadata supplied in this event should be considered as trusted for the user.
    */
    'authenticated'?: boolean = false;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "authenticated",
            "baseName": "authenticated",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return RiskUser.attributeTypeMap;
    }
}

