/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class RoleAppResponse {
  /**
   * Apps unique ID in OneLogin.
   */
  "id"?: number;
  /**
   * App name.
   */
  "name"?: string;
  /**
   * A link to the apps icon url.
   */
  "iconUrl"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "number",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "iconUrl",
      baseName: "icon_url",
      type: "string",
    },
  ];

  static getAttributeTypeMap() {
    return RoleAppResponse.attributeTypeMap;
  }
}
