/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Role {
    'id'?: number;
    'name': string;
    'apps'?: Array<number>;
    'users'?: Array<number>;
    'admins'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "apps",
            "baseName": "apps",
            "type": "Array<number>"
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<number>"
        },
        {
            "name": "admins",
            "baseName": "admins",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return Role.attributeTypeMap;
    }
}

