/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RiskDevice } from './riskDevice';
import { RiskUser } from './riskUser';
import { Session } from './session';
import { Source } from './source';

export class TrackEventRequest {
    /**
    * Verbs are used to distinguish between different types of events.
    */
    'verb': string;
    /**
    * The IP address of the User\'s request.
    */
    'ip': string;
    /**
    * The user agent of the User\'s request.
    */
    'userAgent': string;
    'user': RiskUser;
    'source'?: Source;
    'session'?: Session;
    'device'?: RiskDevice;
    /**
    * Set to the value of the __tdli_fp cookie.
    */
    'fp'?: string;
    /**
    * Date and time of the event in IS08601 format. Useful for preloading old events. Defaults to date time this API request is received.
    */
    'published'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "verb",
            "baseName": "verb",
            "type": "string"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string"
        },
        {
            "name": "userAgent",
            "baseName": "user_agent",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "RiskUser"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "Source"
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "Session"
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "RiskDevice"
        },
        {
            "name": "fp",
            "baseName": "fp",
            "type": "string"
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TrackEventRequest.attributeTypeMap;
    }
}

