/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class VerifyFactorRequest {
    /**
    * OTP code provided by the device or SMS message sent to user.
    */
    'otp'?: string;
    /**
    * ID of the specified device which has been registerd for the given user.
    */
    'deviceId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "otp",
            "baseName": "otp",
            "type": "string"
        },
        {
            "name": "deviceId",
            "baseName": "device_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return VerifyFactorRequest.attributeTypeMap;
    }
}

