/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class VerifyFactorVoice200ResponseInner {
    'id'?: string;
    'status'?: VerifyFactorVoice200ResponseInner.StatusEnum;
    'deviceId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "VerifyFactorVoice200ResponseInner.StatusEnum"
        },
        {
            "name": "deviceId",
            "baseName": "device_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return VerifyFactorVoice200ResponseInner.attributeTypeMap;
    }
}

export namespace VerifyFactorVoice200ResponseInner {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Accepted = <any> 'accepted',
        Rejected = <any> 'rejected'
    }
}
