/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OneLoginApi);
  }
}(this, function(expect, OneLoginApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OneLoginApi.Device();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Device', function() {
    it('should create an instance of Device', function() {
      // uncomment below and update the code to test Device
      //var instance = new OneLoginApi.Device();
      //expect(instance).to.be.a(OneLoginApi.Device);
    });

    it('should have the property deviceId (base name: "device_id")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instance = new OneLoginApi.Device();
      //expect(instance).to.be();
    });

    it('should have the property userDisplayName (base name: "user_display_name")', function() {
      // uncomment below and update the code to test the property userDisplayName
      //var instance = new OneLoginApi.Device();
      //expect(instance).to.be();
    });

    it('should have the property typeDisplayName (base name: "type_display_name")', function() {
      // uncomment below and update the code to test the property typeDisplayName
      //var instance = new OneLoginApi.Device();
      //expect(instance).to.be();
    });

    it('should have the property authFactorName (base name: "auth_factor_name")', function() {
      // uncomment below and update the code to test the property authFactorName
      //var instance = new OneLoginApi.Device();
      //expect(instance).to.be();
    });

    it('should have the property _default (base name: "default")', function() {
      // uncomment below and update the code to test the property _default
      //var instance = new OneLoginApi.Device();
      //expect(instance).to.be();
    });

  });

}));
