/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OneLoginApi);
  }
}(this, function(expect, OneLoginApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OneLoginApi.GetScoreInsights200ResponseScores();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetScoreInsights200ResponseScores', function() {
    it('should create an instance of GetScoreInsights200ResponseScores', function() {
      // uncomment below and update the code to test GetScoreInsights200ResponseScores
      //var instance = new OneLoginApi.GetScoreInsights200ResponseScores();
      //expect(instance).to.be.a(OneLoginApi.GetScoreInsights200ResponseScores);
    });

    it('should have the property minimal (base name: "minimal")', function() {
      // uncomment below and update the code to test the property minimal
      //var instance = new OneLoginApi.GetScoreInsights200ResponseScores();
      //expect(instance).to.be();
    });

    it('should have the property low (base name: "low")', function() {
      // uncomment below and update the code to test the property low
      //var instance = new OneLoginApi.GetScoreInsights200ResponseScores();
      //expect(instance).to.be();
    });

    it('should have the property medium (base name: "medium")', function() {
      // uncomment below and update the code to test the property medium
      //var instance = new OneLoginApi.GetScoreInsights200ResponseScores();
      //expect(instance).to.be();
    });

    it('should have the property high (base name: "high")', function() {
      // uncomment below and update the code to test the property high
      //var instance = new OneLoginApi.GetScoreInsights200ResponseScores();
      //expect(instance).to.be();
    });

    it('should have the property veryHigh (base name: "very_high")', function() {
      // uncomment below and update the code to test the property veryHigh
      //var instance = new OneLoginApi.GetScoreInsights200ResponseScores();
      //expect(instance).to.be();
    });

  });

}));
