/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OneLoginApi);
  }
}(this, function(expect, OneLoginApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListAccessTokenClaims200ResponseInner', function() {
    it('should create an instance of ListAccessTokenClaims200ResponseInner', function() {
      // uncomment below and update the code to test ListAccessTokenClaims200ResponseInner
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be.a(OneLoginApi.ListAccessTokenClaims200ResponseInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property label (base name: "label")', function() {
      // uncomment below and update the code to test the property label
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property userAttributeMappings (base name: "user_attribute_mappings")', function() {
      // uncomment below and update the code to test the property userAttributeMappings
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property userAttributeMacros (base name: "user_attribute_macros")', function() {
      // uncomment below and update the code to test the property userAttributeMacros
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property attributesTransformations (base name: "attributes_transformations")', function() {
      // uncomment below and update the code to test the property attributesTransformations
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property skipIfBlank (base name: "skip_if_blank")', function() {
      // uncomment below and update the code to test the property skipIfBlank
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property values (base name: "values")', function() {
      // uncomment below and update the code to test the property values
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property defaultValues (base name: "default_values")', function() {
      // uncomment below and update the code to test the property defaultValues
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

    it('should have the property provisionedEntitlements (base name: "provisioned_entitlements")', function() {
      // uncomment below and update the code to test the property provisionedEntitlements
      //var instance = new OneLoginApi.ListAccessTokenClaims200ResponseInner();
      //expect(instance).to.be();
    });

  });

}));
