/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ActivateFactorRequest model module.
 * @module model/ActivateFactorRequest
 * @version 0.0.1
 */
class ActivateFactorRequest {
    /**
     * Constructs a new <code>ActivateFactorRequest</code>.
     * @alias module:model/ActivateFactorRequest
     */
    constructor() { 
        
        ActivateFactorRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ActivateFactorRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActivateFactorRequest} obj Optional instance to populate.
     * @return {module:model/ActivateFactorRequest} The populated <code>ActivateFactorRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivateFactorRequest();

            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'Number');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('redirect_to')) {
                obj['redirect_to'] = ApiClient.convertToType(data['redirect_to'], 'String');
            }
            if (data.hasOwnProperty('custom_message')) {
                obj['custom_message'] = ApiClient.convertToType(data['custom_message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Required. Specifies the factor to be verified.
 * @member {Number} device_id
 */
ActivateFactorRequest.prototype['device_id'] = undefined;

/**
 * Optional. Sets the window of time in seconds that the factor must be verified within. 
 * @member {Number} expires_in
 */
ActivateFactorRequest.prototype['expires_in'] = undefined;

/**
 * Optional. Only applies to Email MagicLink factor.
 * @member {String} redirect_to
 */
ActivateFactorRequest.prototype['redirect_to'] = undefined;

/**
 * Optional. Only applies to SMS factor. A message template that will be sent via SMS.
 * @member {String} custom_message
 */
ActivateFactorRequest.prototype['custom_message'] = undefined;






export default ActivateFactorRequest;

