/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddClientAppRequest model module.
 * @module model/AddClientAppRequest
 * @version 0.0.1
 */
class AddClientAppRequest {
    /**
     * Constructs a new <code>AddClientAppRequest</code>.
     * @alias module:model/AddClientAppRequest
     */
    constructor() { 
        
        AddClientAppRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddClientAppRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddClientAppRequest} obj Optional instance to populate.
     * @return {module:model/AddClientAppRequest} The populated <code>AddClientAppRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddClientAppRequest();

            if (data.hasOwnProperty('app_id')) {
                obj['app_id'] = ApiClient.convertToType(data['app_id'], 'Number');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} app_id
 */
AddClientAppRequest.prototype['app_id'] = undefined;

/**
 * @member {Array.<Number>} scopes
 */
AddClientAppRequest.prototype['scopes'] = undefined;






export default AddClientAppRequest;

