/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthServerConfiguration model module.
 * @module model/AuthServerConfiguration
 * @version 0.0.1
 */
class AuthServerConfiguration {
    /**
     * Constructs a new <code>AuthServerConfiguration</code>.
     * @alias module:model/AuthServerConfiguration
     */
    constructor() { 
        
        AuthServerConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthServerConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthServerConfiguration} obj Optional instance to populate.
     * @return {module:model/AuthServerConfiguration} The populated <code>AuthServerConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthServerConfiguration();

            if (data.hasOwnProperty('audiences')) {
                obj['audiences'] = ApiClient.convertToType(data['audiences'], ['String']);
            }
            if (data.hasOwnProperty('refresh_token_expiration_minutes')) {
                obj['refresh_token_expiration_minutes'] = ApiClient.convertToType(data['refresh_token_expiration_minutes'], 'Number');
            }
            if (data.hasOwnProperty('resource_identifier')) {
                obj['resource_identifier'] = ApiClient.convertToType(data['resource_identifier'], 'String');
            }
            if (data.hasOwnProperty('access_token_expiration_minutes')) {
                obj['access_token_expiration_minutes'] = ApiClient.convertToType(data['access_token_expiration_minutes'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} audiences
 */
AuthServerConfiguration.prototype['audiences'] = undefined;

/**
 * @member {Number} refresh_token_expiration_minutes
 */
AuthServerConfiguration.prototype['refresh_token_expiration_minutes'] = undefined;

/**
 * @member {String} resource_identifier
 */
AuthServerConfiguration.prototype['resource_identifier'] = undefined;

/**
 * @member {Number} access_token_expiration_minutes
 */
AuthServerConfiguration.prototype['access_token_expiration_minutes'] = undefined;






export default AuthServerConfiguration;

