/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthMethod from './AuthMethod';

/**
 * The Connector model module.
 * @module model/Connector
 * @version 0.0.1
 */
class Connector {
    /**
     * Constructs a new <code>Connector</code>.
     * @alias module:model/Connector
     */
    constructor() { 
        
        Connector.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Connector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Connector} obj Optional instance to populate.
     * @return {module:model/Connector} The populated <code>Connector</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Connector();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('auth_method')) {
                obj['auth_method'] = AuthMethod.constructFromObject(data['auth_method']);
            }
            if (data.hasOwnProperty('allows_new_parameters')) {
                obj['allows_new_parameters'] = ApiClient.convertToType(data['allows_new_parameters'], 'Boolean');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The connectors unique ID in OneLogin.
 * @member {Number} id
 */
Connector.prototype['id'] = undefined;

/**
 * The name of the connector.
 * @member {String} name
 */
Connector.prototype['name'] = undefined;

/**
 * @member {module:model/AuthMethod} auth_method
 */
Connector.prototype['auth_method'] = undefined;

/**
 * Indicates if apps created using this connector will be allowed to create custom parameters.
 * @member {Boolean} allows_new_parameters
 */
Connector.prototype['allows_new_parameters'] = undefined;

/**
 * A link to the apps icon url.
 * @member {String} icon_url
 */
Connector.prototype['icon_url'] = undefined;






export default Connector;

