/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateEnvironmentVariableRequest model module.
 * @module model/CreateEnvironmentVariableRequest
 * @version 0.0.1
 */
class CreateEnvironmentVariableRequest {
    /**
     * Constructs a new <code>CreateEnvironmentVariableRequest</code>.
     * @alias module:model/CreateEnvironmentVariableRequest
     * @param name {String} The name for the environment variable that will be used to retrieve the value from a hook function.
     * @param value {String} The secret value that will be encrypted at rest and injected in applicable hook functions at run time.
     */
    constructor(name, value) { 
        
        CreateEnvironmentVariableRequest.initialize(this, name, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, value) { 
        obj['name'] = name;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>CreateEnvironmentVariableRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateEnvironmentVariableRequest} obj Optional instance to populate.
     * @return {module:model/CreateEnvironmentVariableRequest} The populated <code>CreateEnvironmentVariableRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateEnvironmentVariableRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name for the environment variable that will be used to retrieve the value from a hook function.
 * @member {String} name
 */
CreateEnvironmentVariableRequest.prototype['name'] = undefined;

/**
 * The secret value that will be encrypted at rest and injected in applicable hook functions at run time.
 * @member {String} value
 */
CreateEnvironmentVariableRequest.prototype['value'] = undefined;






export default CreateEnvironmentVariableRequest;

