/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthServerConfiguration from './AuthServerConfiguration';

/**
 * The CreateAuthorizationServerRequest model module.
 * @module model/CreateAuthorizationServerRequest
 * @version 0.0.1
 */
class CreateAuthorizationServerRequest {
    /**
     * Constructs a new <code>CreateAuthorizationServerRequest</code>.
     * @alias module:model/CreateAuthorizationServerRequest
     */
    constructor() { 
        
        CreateAuthorizationServerRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateAuthorizationServerRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateAuthorizationServerRequest} obj Optional instance to populate.
     * @return {module:model/CreateAuthorizationServerRequest} The populated <code>CreateAuthorizationServerRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAuthorizationServerRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('configuration')) {
                obj['configuration'] = AuthServerConfiguration.constructFromObject(data['configuration']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CreateAuthorizationServerRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
CreateAuthorizationServerRequest.prototype['description'] = undefined;

/**
 * @member {module:model/AuthServerConfiguration} configuration
 */
CreateAuthorizationServerRequest.prototype['configuration'] = undefined;






export default CreateAuthorizationServerRequest;

