/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Device model module.
 * @module model/Device
 * @version 0.0.1
 */
class Device {
    /**
     * Constructs a new <code>Device</code>.
     * @alias module:model/Device
     */
    constructor() { 
        
        Device.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Device</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Device} obj Optional instance to populate.
     * @return {module:model/Device} The populated <code>Device</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Device();

            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
            if (data.hasOwnProperty('user_display_name')) {
                obj['user_display_name'] = ApiClient.convertToType(data['user_display_name'], 'String');
            }
            if (data.hasOwnProperty('type_display_name')) {
                obj['type_display_name'] = ApiClient.convertToType(data['type_display_name'], 'String');
            }
            if (data.hasOwnProperty('auth_factor_name')) {
                obj['auth_factor_name'] = ApiClient.convertToType(data['auth_factor_name'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} device_id
 */
Device.prototype['device_id'] = undefined;

/**
 * @member {String} user_display_name
 */
Device.prototype['user_display_name'] = undefined;

/**
 * @member {String} type_display_name
 */
Device.prototype['type_display_name'] = undefined;

/**
 * @member {String} auth_factor_name
 */
Device.prototype['auth_factor_name'] = undefined;

/**
 * @member {Boolean} default
 */
Device.prototype['default'] = undefined;






export default Device;

