/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Envvar model module.
 * @module model/Envvar
 * @version 0.0.1
 */
class Envvar {
    /**
     * Constructs a new <code>Envvar</code>.
     * @alias module:model/Envvar
     */
    constructor() { 
        
        Envvar.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Envvar</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Envvar} obj Optional instance to populate.
     * @return {module:model/Envvar} The populated <code>Envvar</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Envvar();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A unique identifier for the Hook Environment Variable
 * @member {String} id
 */
Envvar.prototype['id'] = undefined;

/**
 * The name of the environment variable.
 * @member {String} name
 */
Envvar.prototype['name'] = undefined;

/**
 * The ISO8601 formatted date that the environment variable was created.
 * @member {String} created_at
 */
Envvar.prototype['created_at'] = undefined;

/**
 * The ISO8601 formatted date that the environment variable was last updated.
 * @member {String} updated_at
 */
Envvar.prototype['updated_at'] = undefined;






export default Envvar;

