/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorStatusErrorsInner from './ErrorStatusErrorsInner';

/**
 * The ErrorStatus model module.
 * @module model/ErrorStatus
 * @version 0.0.1
 */
class ErrorStatus {
    /**
     * Constructs a new <code>ErrorStatus</code>.
     * @alias module:model/ErrorStatus
     */
    constructor() { 
        
        ErrorStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ErrorStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorStatus} obj Optional instance to populate.
     * @return {module:model/ErrorStatus} The populated <code>ErrorStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorStatus();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [ErrorStatusErrorsInner]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} code
 */
ErrorStatus.prototype['code'] = undefined;

/**
 * @member {String} message
 */
ErrorStatus.prototype['message'] = undefined;

/**
 * @member {Array.<module:model/ErrorStatusErrorsInner>} errors
 */
ErrorStatus.prototype['errors'] = undefined;






export default ErrorStatus;

