/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ErrorStatusErrorsInner model module.
 * @module model/ErrorStatusErrorsInner
 * @version 0.0.1
 */
class ErrorStatusErrorsInner {
    /**
     * Constructs a new <code>ErrorStatusErrorsInner</code>.
     * @alias module:model/ErrorStatusErrorsInner
     */
    constructor() { 
        
        ErrorStatusErrorsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ErrorStatusErrorsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorStatusErrorsInner} obj Optional instance to populate.
     * @return {module:model/ErrorStatusErrorsInner} The populated <code>ErrorStatusErrorsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorStatusErrorsInner();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} field
 */
ErrorStatusErrorsInner.prototype['field'] = undefined;

/**
 * @member {Array.<String>} message
 */
ErrorStatusErrorsInner.prototype['message'] = undefined;






export default ErrorStatusErrorsInner;

