/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenerateMfaToken200Response model module.
 * @module model/GenerateMfaToken200Response
 * @version 0.0.1
 */
class GenerateMfaToken200Response {
    /**
     * Constructs a new <code>GenerateMfaToken200Response</code>.
     * @alias module:model/GenerateMfaToken200Response
     */
    constructor() { 
        
        GenerateMfaToken200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenerateMfaToken200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateMfaToken200Response} obj Optional instance to populate.
     * @return {module:model/GenerateMfaToken200Response} The populated <code>GenerateMfaToken200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateMfaToken200Response();

            if (data.hasOwnProperty('mfa_token')) {
                obj['mfa_token'] = ApiClient.convertToType(data['mfa_token'], 'String');
            }
            if (data.hasOwnProperty('reusable')) {
                obj['reusable'] = ApiClient.convertToType(data['reusable'], 'Boolean');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Token can function as a temporary MFA token. It can be used to authenticate for any app when valid.
 * @member {String} mfa_token
 */
GenerateMfaToken200Response.prototype['mfa_token'] = undefined;

/**
 * true indcates the token can be used multiple times. false indicates the token is invalid after a single use
 * @member {Boolean} reusable
 */
GenerateMfaToken200Response.prototype['reusable'] = undefined;

/**
 * Defines the expiration time and date for the token. Format is UTC time.
 * @member {String} expires_at
 */
GenerateMfaToken200Response.prototype['expires_at'] = undefined;

/**
 * Defines the expiration time and date for the token. Format is UTC time.
 * @member {String} device_id
 */
GenerateMfaToken200Response.prototype['device_id'] = undefined;






export default GenerateMfaToken200Response;

