/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GenerateMfaToken422ResponseDetails from './GenerateMfaToken422ResponseDetails';

/**
 * The GenerateMfaToken422Response model module.
 * @module model/GenerateMfaToken422Response
 * @version 0.0.1
 */
class GenerateMfaToken422Response {
    /**
     * Constructs a new <code>GenerateMfaToken422Response</code>.
     * @alias module:model/GenerateMfaToken422Response
     */
    constructor() { 
        
        GenerateMfaToken422Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenerateMfaToken422Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateMfaToken422Response} obj Optional instance to populate.
     * @return {module:model/GenerateMfaToken422Response} The populated <code>GenerateMfaToken422Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateMfaToken422Response();

            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = GenerateMfaToken422ResponseDetails.constructFromObject(data['details']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} statusCode
 */
GenerateMfaToken422Response.prototype['statusCode'] = undefined;

/**
 * @member {String} name
 */
GenerateMfaToken422Response.prototype['name'] = undefined;

/**
 * @member {String} message
 */
GenerateMfaToken422Response.prototype['message'] = undefined;

/**
 * @member {module:model/GenerateMfaToken422ResponseDetails} details
 */
GenerateMfaToken422Response.prototype['details'] = undefined;






export default GenerateMfaToken422Response;

