/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status from './Status';

/**
 * The GenerateToken400Response model module.
 * @module model/GenerateToken400Response
 * @version 0.0.1
 */
class GenerateToken400Response {
    /**
     * Constructs a new <code>GenerateToken400Response</code>.
     * @alias module:model/GenerateToken400Response
     */
    constructor() { 
        
        GenerateToken400Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenerateToken400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateToken400Response} obj Optional instance to populate.
     * @return {module:model/GenerateToken400Response} The populated <code>GenerateToken400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateToken400Response();

            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Status} status
 */
GenerateToken400Response.prototype['status'] = undefined;






export default GenerateToken400Response;

