/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GenerateTokenRequest model module.
 * @module model/GenerateTokenRequest
 * @version 0.0.1
 */
class GenerateTokenRequest {
    /**
     * Constructs a new <code>GenerateTokenRequest</code>.
     * @alias module:model/GenerateTokenRequest
     */
    constructor() { 
        
        GenerateTokenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GenerateTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateTokenRequest} obj Optional instance to populate.
     * @return {module:model/GenerateTokenRequest} The populated <code>GenerateTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateTokenRequest();

            if (data.hasOwnProperty('grant_type')) {
                obj['grant_type'] = ApiClient.convertToType(data['grant_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GenerateTokenRequest.GrantTypeEnum} grant_type
 */
GenerateTokenRequest.prototype['grant_type'] = undefined;





/**
 * Allowed values for the <code>grant_type</code> property.
 * @enum {String}
 * @readonly
 */
GenerateTokenRequest['GrantTypeEnum'] = {

    /**
     * value: "client_credentials"
     * @const
     */
    "client_credentials": "client_credentials"
};



export default GenerateTokenRequest;

