/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAvailableFactors200ResponseInner model module.
 * @module model/GetAvailableFactors200ResponseInner
 * @version 0.0.1
 */
class GetAvailableFactors200ResponseInner {
    /**
     * Constructs a new <code>GetAvailableFactors200ResponseInner</code>.
     * @alias module:model/GetAvailableFactors200ResponseInner
     */
    constructor() { 
        
        GetAvailableFactors200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAvailableFactors200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAvailableFactors200ResponseInner} obj Optional instance to populate.
     * @return {module:model/GetAvailableFactors200ResponseInner} The populated <code>GetAvailableFactors200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAvailableFactors200ResponseInner();

            if (data.hasOwnProperty('factor_id')) {
                obj['factor_id'] = ApiClient.convertToType(data['factor_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('auth_factor_name')) {
                obj['auth_factor_name'] = ApiClient.convertToType(data['auth_factor_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Identifier for the factor which will be used for user enrollment
 * @member {Number} factor_id
 */
GetAvailableFactors200ResponseInner.prototype['factor_id'] = undefined;

/**
 * Authentication factor name, as it appears to administrators in OneLogin.
 * @member {String} name
 */
GetAvailableFactors200ResponseInner.prototype['name'] = undefined;

/**
 * Internal use only
 * @member {String} auth_factor_name
 */
GetAvailableFactors200ResponseInner.prototype['auth_factor_name'] = undefined;






export default GetAvailableFactors200ResponseInner;

