/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetClientApps200ResponseInnerScopesInner model module.
 * @module model/GetClientApps200ResponseInnerScopesInner
 * @version 0.0.1
 */
class GetClientApps200ResponseInnerScopesInner {
    /**
     * Constructs a new <code>GetClientApps200ResponseInnerScopesInner</code>.
     * @alias module:model/GetClientApps200ResponseInnerScopesInner
     */
    constructor() { 
        
        GetClientApps200ResponseInnerScopesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetClientApps200ResponseInnerScopesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetClientApps200ResponseInnerScopesInner} obj Optional instance to populate.
     * @return {module:model/GetClientApps200ResponseInnerScopesInner} The populated <code>GetClientApps200ResponseInnerScopesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetClientApps200ResponseInnerScopesInner();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
GetClientApps200ResponseInnerScopesInner.prototype['description'] = undefined;

/**
 * @member {String} value
 */
GetClientApps200ResponseInnerScopesInner.prototype['value'] = undefined;

/**
 * @member {Number} id
 */
GetClientApps200ResponseInnerScopesInner.prototype['id'] = undefined;






export default GetClientApps200ResponseInnerScopesInner;

