/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetClientApps200ResponseInnerScopesInner from './GetClientApps200ResponseInnerScopesInner';

/**
 * The GetClientApps200ResponseInner model module.
 * @module model/GetClientApps200ResponseInner
 * @version 0.0.1
 */
class GetClientApps200ResponseInner {
    /**
     * Constructs a new <code>GetClientApps200ResponseInner</code>.
     * @alias module:model/GetClientApps200ResponseInner
     */
    constructor() { 
        
        GetClientApps200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetClientApps200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetClientApps200ResponseInner} obj Optional instance to populate.
     * @return {module:model/GetClientApps200ResponseInner} The populated <code>GetClientApps200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetClientApps200ResponseInner();

            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], [GetClientApps200ResponseInnerScopesInner]);
            }
            if (data.hasOwnProperty('app_id')) {
                obj['app_id'] = ApiClient.convertToType(data['app_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('api_auth_id')) {
                obj['api_auth_id'] = ApiClient.convertToType(data['api_auth_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GetClientApps200ResponseInnerScopesInner>} scopes
 */
GetClientApps200ResponseInner.prototype['scopes'] = undefined;

/**
 * @member {Number} app_id
 */
GetClientApps200ResponseInner.prototype['app_id'] = undefined;

/**
 * @member {String} name
 */
GetClientApps200ResponseInner.prototype['name'] = undefined;

/**
 * @member {Number} api_auth_id
 */
GetClientApps200ResponseInner.prototype['api_auth_id'] = undefined;






export default GetClientApps200ResponseInner;

