/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetRiskScore400Response model module.
 * @module model/GetRiskScore400Response
 * @version 0.0.1
 */
class GetRiskScore400Response {
    /**
     * Constructs a new <code>GetRiskScore400Response</code>.
     * @alias module:model/GetRiskScore400Response
     */
    constructor() { 
        
        GetRiskScore400Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRiskScore400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRiskScore400Response} obj Optional instance to populate.
     * @return {module:model/GetRiskScore400Response} The populated <code>GetRiskScore400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRiskScore400Response();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} messages
 */
GetRiskScore400Response.prototype['messages'] = undefined;






export default GetRiskScore400Response;

