/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetRateLimit200ResponseData from './GetRateLimit200ResponseData';
import Status from './Status';

/**
 * The GetRateLimit200Response model module.
 * @module model/GetRateLimit200Response
 * @version 0.0.1
 */
class GetRateLimit200Response {
    /**
     * Constructs a new <code>GetRateLimit200Response</code>.
     * @alias module:model/GetRateLimit200Response
     */
    constructor() { 
        
        GetRateLimit200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRateLimit200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRateLimit200Response} obj Optional instance to populate.
     * @return {module:model/GetRateLimit200Response} The populated <code>GetRateLimit200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRateLimit200Response();

            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GetRateLimit200ResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Status} status
 */
GetRateLimit200Response.prototype['status'] = undefined;

/**
 * @member {module:model/GetRateLimit200ResponseData} data
 */
GetRateLimit200Response.prototype['data'] = undefined;






export default GetRateLimit200Response;

