/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RiskDevice from './RiskDevice';
import RiskUser from './RiskUser';
import Session from './Session';
import Source from './Source';

/**
 * The GetRiskScoreRequest model module.
 * @module model/GetRiskScoreRequest
 * @version 0.0.1
 */
class GetRiskScoreRequest {
    /**
     * Constructs a new <code>GetRiskScoreRequest</code>.
     * @alias module:model/GetRiskScoreRequest
     * @param ip {String} The IP address of the User's request.
     * @param userAgent {String} The user agent of the User's request.
     * @param user {module:model/RiskUser} 
     */
    constructor(ip, userAgent, user) { 
        
        GetRiskScoreRequest.initialize(this, ip, userAgent, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ip, userAgent, user) { 
        obj['ip'] = ip;
        obj['user_agent'] = userAgent;
        obj['user'] = user;
    }

    /**
     * Constructs a <code>GetRiskScoreRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRiskScoreRequest} obj Optional instance to populate.
     * @return {module:model/GetRiskScoreRequest} The populated <code>GetRiskScoreRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRiskScoreRequest();

            if (data.hasOwnProperty('ip')) {
                obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
            }
            if (data.hasOwnProperty('user_agent')) {
                obj['user_agent'] = ApiClient.convertToType(data['user_agent'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = RiskUser.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = Source.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('session')) {
                obj['session'] = Session.constructFromObject(data['session']);
            }
            if (data.hasOwnProperty('device')) {
                obj['device'] = RiskDevice.constructFromObject(data['device']);
            }
            if (data.hasOwnProperty('fp')) {
                obj['fp'] = ApiClient.convertToType(data['fp'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The IP address of the User's request.
 * @member {String} ip
 */
GetRiskScoreRequest.prototype['ip'] = undefined;

/**
 * The user agent of the User's request.
 * @member {String} user_agent
 */
GetRiskScoreRequest.prototype['user_agent'] = undefined;

/**
 * @member {module:model/RiskUser} user
 */
GetRiskScoreRequest.prototype['user'] = undefined;

/**
 * @member {module:model/Source} source
 */
GetRiskScoreRequest.prototype['source'] = undefined;

/**
 * @member {module:model/Session} session
 */
GetRiskScoreRequest.prototype['session'] = undefined;

/**
 * @member {module:model/RiskDevice} device
 */
GetRiskScoreRequest.prototype['device'] = undefined;

/**
 * Set to the value of the __tdli_fp cookie.
 * @member {String} fp
 */
GetRiskScoreRequest.prototype['fp'] = undefined;






export default GetRiskScoreRequest;

