/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetRiskScore200Response model module.
 * @module model/GetRiskScore200Response
 * @version 0.0.1
 */
class GetRiskScore200Response {
    /**
     * Constructs a new <code>GetRiskScore200Response</code>.
     * @alias module:model/GetRiskScore200Response
     */
    constructor() { 
        
        GetRiskScore200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetRiskScore200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetRiskScore200Response} obj Optional instance to populate.
     * @return {module:model/GetRiskScore200Response} The populated <code>GetRiskScore200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetRiskScore200Response();

            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('triggers')) {
                obj['triggers'] = ApiClient.convertToType(data['triggers'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * A risk score 0 is low risk and 100 is the highest risk level possible.
 * @member {Number} score
 */
GetRiskScore200Response.prototype['score'] = undefined;

/**
 * Triggers are indicators of some of the key items that influenced the risk score.
 * @member {Array.<String>} triggers
 */
GetRiskScore200Response.prototype['triggers'] = undefined;






export default GetRiskScore200Response;

