/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetScoreInsights200ResponseScores model module.
 * @module model/GetScoreInsights200ResponseScores
 * @version 0.0.1
 */
class GetScoreInsights200ResponseScores {
    /**
     * Constructs a new <code>GetScoreInsights200ResponseScores</code>.
     * @alias module:model/GetScoreInsights200ResponseScores
     */
    constructor() { 
        
        GetScoreInsights200ResponseScores.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetScoreInsights200ResponseScores</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetScoreInsights200ResponseScores} obj Optional instance to populate.
     * @return {module:model/GetScoreInsights200ResponseScores} The populated <code>GetScoreInsights200ResponseScores</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetScoreInsights200ResponseScores();

            if (data.hasOwnProperty('minimal')) {
                obj['minimal'] = ApiClient.convertToType(data['minimal'], 'Number');
            }
            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], 'Number');
            }
            if (data.hasOwnProperty('medium')) {
                obj['medium'] = ApiClient.convertToType(data['medium'], 'Number');
            }
            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
            if (data.hasOwnProperty('very_high')) {
                obj['very_high'] = ApiClient.convertToType(data['very_high'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} minimal
 */
GetScoreInsights200ResponseScores.prototype['minimal'] = undefined;

/**
 * @member {Number} low
 */
GetScoreInsights200ResponseScores.prototype['low'] = undefined;

/**
 * @member {Number} medium
 */
GetScoreInsights200ResponseScores.prototype['medium'] = undefined;

/**
 * @member {Number} high
 */
GetScoreInsights200ResponseScores.prototype['high'] = undefined;

/**
 * @member {Number} very_high
 */
GetScoreInsights200ResponseScores.prototype['very_high'] = undefined;






export default GetScoreInsights200ResponseScores;

