/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetScoreInsights200ResponseScores from './GetScoreInsights200ResponseScores';

/**
 * The GetScoreInsights200Response model module.
 * @module model/GetScoreInsights200Response
 * @version 0.0.1
 */
class GetScoreInsights200Response {
    /**
     * Constructs a new <code>GetScoreInsights200Response</code>.
     * @alias module:model/GetScoreInsights200Response
     */
    constructor() { 
        
        GetScoreInsights200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetScoreInsights200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetScoreInsights200Response} obj Optional instance to populate.
     * @return {module:model/GetScoreInsights200Response} The populated <code>GetScoreInsights200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetScoreInsights200Response();

            if (data.hasOwnProperty('scores')) {
                obj['scores'] = GetScoreInsights200ResponseScores.constructFromObject(data['scores']);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetScoreInsights200ResponseScores} scores
 */
GetScoreInsights200Response.prototype['scores'] = undefined;

/**
 * @member {Number} total
 */
GetScoreInsights200Response.prototype['total'] = undefined;






export default GetScoreInsights200Response;

