/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetUserApps200ResponseInner model module.
 * @module model/GetUserApps200ResponseInner
 * @version 0.0.1
 */
class GetUserApps200ResponseInner {
    /**
     * Constructs a new <code>GetUserApps200ResponseInner</code>.
     * @alias module:model/GetUserApps200ResponseInner
     */
    constructor() { 
        
        GetUserApps200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetUserApps200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetUserApps200ResponseInner} obj Optional instance to populate.
     * @return {module:model/GetUserApps200ResponseInner} The populated <code>GetUserApps200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetUserApps200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('icon_url')) {
                obj['icon_url'] = ApiClient.convertToType(data['icon_url'], 'String');
            }
            if (data.hasOwnProperty('extension')) {
                obj['extension'] = ApiClient.convertToType(data['extension'], 'Boolean');
            }
            if (data.hasOwnProperty('login_id')) {
                obj['login_id'] = ApiClient.convertToType(data['login_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('provisioning_status')) {
                obj['provisioning_status'] = ApiClient.convertToType(data['provisioning_status'], 'String');
            }
            if (data.hasOwnProperty('provisioning_state')) {
                obj['provisioning_state'] = ApiClient.convertToType(data['provisioning_state'], 'String');
            }
            if (data.hasOwnProperty('provisioning_enabled')) {
                obj['provisioning_enabled'] = ApiClient.convertToType(data['provisioning_enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The App ID
 * @member {Number} id
 */
GetUserApps200ResponseInner.prototype['id'] = undefined;

/**
 * A url for the icon that represents the app in the OneLogin portal
 * @member {String} icon_url
 */
GetUserApps200ResponseInner.prototype['icon_url'] = undefined;

/**
 * Boolean that indicates if the OneLogin browser extension is required to launch this app.
 * @member {Boolean} extension
 */
GetUserApps200ResponseInner.prototype['extension'] = undefined;

/**
 * Unqiue identifier for this user and app combination.
 * @member {Number} login_id
 */
GetUserApps200ResponseInner.prototype['login_id'] = undefined;

/**
 * The name of the app.
 * @member {String} name
 */
GetUserApps200ResponseInner.prototype['name'] = undefined;

/**
 * @member {module:model/GetUserApps200ResponseInner.ProvisioningStatusEnum} provisioning_status
 */
GetUserApps200ResponseInner.prototype['provisioning_status'] = undefined;

/**
 * If provisioning is enabled this indicates the state of provisioning for the given user.
 * @member {module:model/GetUserApps200ResponseInner.ProvisioningStateEnum} provisioning_state
 */
GetUserApps200ResponseInner.prototype['provisioning_state'] = undefined;

/**
 * Indicates if provisioning is enabled for this app.
 * @member {Boolean} provisioning_enabled
 */
GetUserApps200ResponseInner.prototype['provisioning_enabled'] = undefined;





/**
 * Allowed values for the <code>provisioning_status</code> property.
 * @enum {String}
 * @readonly
 */
GetUserApps200ResponseInner['ProvisioningStatusEnum'] = {

    /**
     * value: "enabling"
     * @const
     */
    "enabling": "enabling",

    /**
     * value: "disabling"
     * @const
     */
    "disabling": "disabling",

    /**
     * value: "enabling_pending_approval"
     * @const
     */
    "enabling_pending_approval": "enabling_pending_approval",

    /**
     * value: "disabling_pendding_approval"
     * @const
     */
    "disabling_pendding_approval": "disabling_pendding_approval",

    /**
     * value: "enabled"
     * @const
     */
    "enabled": "enabled",

    /**
     * value: "disabled"
     * @const
     */
    "disabled": "disabled",

    /**
     * value: "disabling_failed"
     * @const
     */
    "disabling_failed": "disabling_failed",

    /**
     * value: "enabling_failed"
     * @const
     */
    "enabling_failed": "enabling_failed"
};


/**
 * Allowed values for the <code>provisioning_state</code> property.
 * @enum {String}
 * @readonly
 */
GetUserApps200ResponseInner['ProvisioningStateEnum'] = {

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown",

    /**
     * value: "provisioning"
     * @const
     */
    "provisioning": "provisioning",

    /**
     * value: "modifying"
     * @const
     */
    "modifying": "modifying",

    /**
     * value: "deleting"
     * @const
     */
    "deleting": "deleting",

    /**
     * value: "provisioning_pending_approval"
     * @const
     */
    "provisioning_pending_approval": "provisioning_pending_approval",

    /**
     * value: "deleting_pending_approval"
     * @const
     */
    "deleting_pending_approval": "deleting_pending_approval",

    /**
     * value: "modifying_pending_approval"
     * @const
     */
    "modifying_pending_approval": "modifying_pending_approval",

    /**
     * value: "linking"
     * @const
     */
    "linking": "linking",

    /**
     * value: "provisioned"
     * @const
     */
    "provisioned": "provisioned",

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "modifying_failed"
     * @const
     */
    "modifying_failed": "modifying_failed",

    /**
     * value: "provisioning_failed"
     * @const
     */
    "provisioning_failed": "provisioning_failed",

    /**
     * value: "deleting_failed"
     * @const
     */
    "deleting_failed": "deleting_failed",

    /**
     * value: "linking_failed"
     * @const
     */
    "linking_failed": "linking_failed",

    /**
     * value: "disabled"
     * @const
     */
    "disabled": "disabled",

    /**
     * value: "nonexistent"
     * @const
     */
    "nonexistent": "nonexistent",

    /**
     * value: "modifying_pending_approval_then_disabled"
     * @const
     */
    "modifying_pending_approval_then_disabled": "modifying_pending_approval_then_disabled"
};



export default GetUserApps200ResponseInner;

