/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HookOptions model module.
 * @module model/HookOptions
 * @version 0.0.1
 */
class HookOptions {
    /**
     * Constructs a new <code>HookOptions</code>.
     * A set of attributes allow control over the information that is included in the hook context.
     * @alias module:model/HookOptions
     */
    constructor() { 
        
        HookOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HookOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HookOptions} obj Optional instance to populate.
     * @return {module:model/HookOptions} The populated <code>HookOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HookOptions();

            if (data.hasOwnProperty('risk_enabled')) {
                obj['risk_enabled'] = ApiClient.convertToType(data['risk_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('location_enabled')) {
                obj['location_enabled'] = ApiClient.convertToType(data['location_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('mfa_device_info_enabled')) {
                obj['mfa_device_info_enabled'] = ApiClient.convertToType(data['mfa_device_info_enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} risk_enabled
 */
HookOptions.prototype['risk_enabled'] = undefined;

/**
 * @member {Boolean} location_enabled
 */
HookOptions.prototype['location_enabled'] = undefined;

/**
 * @member {Boolean} mfa_device_info_enabled
 */
HookOptions.prototype['mfa_device_info_enabled'] = undefined;






export default HookOptions;

