/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListActions200ResponseInner model module.
 * @module model/ListActions200ResponseInner
 * @version 0.0.1
 */
class ListActions200ResponseInner {
    /**
     * Constructs a new <code>ListActions200ResponseInner</code>.
     * @alias module:model/ListActions200ResponseInner
     */
    constructor() { 
        
        ListActions200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListActions200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListActions200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ListActions200ResponseInner} The populated <code>ListActions200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListActions200ResponseInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the Action.
 * @member {String} name
 */
ListActions200ResponseInner.prototype['name'] = undefined;

/**
 * The unique identifier of the action. This should be used when defining actions for a User Mapping.
 * @member {String} value
 */
ListActions200ResponseInner.prototype['value'] = undefined;






export default ListActions200ResponseInner;

