/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListAccessTokenClaims200ResponseInner model module.
 * @module model/ListAccessTokenClaims200ResponseInner
 * @version 0.0.1
 */
class ListAccessTokenClaims200ResponseInner {
    /**
     * Constructs a new <code>ListAccessTokenClaims200ResponseInner</code>.
     * @alias module:model/ListAccessTokenClaims200ResponseInner
     */
    constructor() { 
        
        ListAccessTokenClaims200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListAccessTokenClaims200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListAccessTokenClaims200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ListAccessTokenClaims200ResponseInner} The populated <code>ListAccessTokenClaims200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListAccessTokenClaims200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('user_attribute_mappings')) {
                obj['user_attribute_mappings'] = ApiClient.convertToType(data['user_attribute_mappings'], 'String');
            }
            if (data.hasOwnProperty('user_attribute_macros')) {
                obj['user_attribute_macros'] = ApiClient.convertToType(data['user_attribute_macros'], 'String');
            }
            if (data.hasOwnProperty('attributes_transformations')) {
                obj['attributes_transformations'] = ApiClient.convertToType(data['attributes_transformations'], 'String');
            }
            if (data.hasOwnProperty('skip_if_blank')) {
                obj['skip_if_blank'] = ApiClient.convertToType(data['skip_if_blank'], 'Boolean');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], ['String']);
            }
            if (data.hasOwnProperty('default_values')) {
                obj['default_values'] = ApiClient.convertToType(data['default_values'], 'String');
            }
            if (data.hasOwnProperty('provisioned_entitlements')) {
                obj['provisioned_entitlements'] = ApiClient.convertToType(data['provisioned_entitlements'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ListAccessTokenClaims200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} label
 */
ListAccessTokenClaims200ResponseInner.prototype['label'] = undefined;

/**
 * @member {String} user_attribute_mappings
 */
ListAccessTokenClaims200ResponseInner.prototype['user_attribute_mappings'] = undefined;

/**
 * @member {String} user_attribute_macros
 */
ListAccessTokenClaims200ResponseInner.prototype['user_attribute_macros'] = undefined;

/**
 * @member {String} attributes_transformations
 */
ListAccessTokenClaims200ResponseInner.prototype['attributes_transformations'] = undefined;

/**
 * @member {Boolean} skip_if_blank
 */
ListAccessTokenClaims200ResponseInner.prototype['skip_if_blank'] = undefined;

/**
 * @member {Array.<String>} values
 */
ListAccessTokenClaims200ResponseInner.prototype['values'] = undefined;

/**
 * @member {String} default_values
 */
ListAccessTokenClaims200ResponseInner.prototype['default_values'] = undefined;

/**
 * @member {Boolean} provisioned_entitlements
 */
ListAccessTokenClaims200ResponseInner.prototype['provisioned_entitlements'] = undefined;






export default ListAccessTokenClaims200ResponseInner;

