/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListAuthorizationServers200ResponseInnerConfiguration model module.
 * @module model/ListAuthorizationServers200ResponseInnerConfiguration
 * @version 0.0.1
 */
class ListAuthorizationServers200ResponseInnerConfiguration {
    /**
     * Constructs a new <code>ListAuthorizationServers200ResponseInnerConfiguration</code>.
     * @alias module:model/ListAuthorizationServers200ResponseInnerConfiguration
     */
    constructor() { 
        
        ListAuthorizationServers200ResponseInnerConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListAuthorizationServers200ResponseInnerConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListAuthorizationServers200ResponseInnerConfiguration} obj Optional instance to populate.
     * @return {module:model/ListAuthorizationServers200ResponseInnerConfiguration} The populated <code>ListAuthorizationServers200ResponseInnerConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListAuthorizationServers200ResponseInnerConfiguration();

            if (data.hasOwnProperty('resource_identifier')) {
                obj['resource_identifier'] = ApiClient.convertToType(data['resource_identifier'], 'String');
            }
            if (data.hasOwnProperty('audiences')) {
                obj['audiences'] = ApiClient.convertToType(data['audiences'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} resource_identifier
 */
ListAuthorizationServers200ResponseInnerConfiguration.prototype['resource_identifier'] = undefined;

/**
 * @member {Array.<String>} audiences
 */
ListAuthorizationServers200ResponseInnerConfiguration.prototype['audiences'] = undefined;






export default ListAuthorizationServers200ResponseInnerConfiguration;

