/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ListAppUsers200ResponseInner model module.
 * @module model/ListAppUsers200ResponseInner
 * @version 0.0.1
 */
class ListAppUsers200ResponseInner {
    /**
     * Constructs a new <code>ListAppUsers200ResponseInner</code>.
     * @alias module:model/ListAppUsers200ResponseInner
     */
    constructor() { 
        
        ListAppUsers200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListAppUsers200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListAppUsers200ResponseInner} obj Optional instance to populate.
     * @return {module:model/ListAppUsers200ResponseInner} The populated <code>ListAppUsers200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListAppUsers200ResponseInner();

            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} firstname
 */
ListAppUsers200ResponseInner.prototype['firstname'] = undefined;

/**
 * @member {Number} id
 */
ListAppUsers200ResponseInner.prototype['id'] = undefined;

/**
 * @member {String} email
 */
ListAppUsers200ResponseInner.prototype['email'] = undefined;

/**
 * @member {String} lastname
 */
ListAppUsers200ResponseInner.prototype['lastname'] = undefined;

/**
 * @member {String} username
 */
ListAppUsers200ResponseInner.prototype['username'] = undefined;






export default ListAppUsers200ResponseInner;

