/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Registration model module.
 * @module model/Registration
 * @version 0.0.1
 */
class Registration {
    /**
     * Constructs a new <code>Registration</code>.
     * @alias module:model/Registration
     */
    constructor() { 
        
        Registration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Registration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Registration} obj Optional instance to populate.
     * @return {module:model/Registration} The populated <code>Registration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Registration();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Registration identifier.
 * @member {String} id
 */
Registration.prototype['id'] = undefined;

/**
 * pending registration has not been completed successfully. accepted registration has successfully completed.
 * @member {module:model/Registration.StatusEnum} status
 */
Registration.prototype['status'] = undefined;

/**
 * Device id to be used with Verify the Factor.
 * @member {String} device_id
 */
Registration.prototype['device_id'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Registration['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "accepted"
     * @const
     */
    "accepted": "accepted"
};



export default Registration;

