/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoveRoleUsersRequest model module.
 * @module model/RemoveRoleUsersRequest
 * @version 0.0.1
 */
class RemoveRoleUsersRequest {
    /**
     * Constructs a new <code>RemoveRoleUsersRequest</code>.
     * @alias module:model/RemoveRoleUsersRequest
     */
    constructor() { 
        
        RemoveRoleUsersRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RemoveRoleUsersRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveRoleUsersRequest} obj Optional instance to populate.
     * @return {module:model/RemoveRoleUsersRequest} The populated <code>RemoveRoleUsersRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveRoleUsersRequest();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} user_id
 */
RemoveRoleUsersRequest.prototype['user_id'] = undefined;






export default RemoveRoleUsersRequest;

