/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RiskDevice model module.
 * @module model/RiskDevice
 * @version 0.0.1
 */
class RiskDevice {
    /**
     * Constructs a new <code>RiskDevice</code>.
     * Information about the device being used.
     * @alias module:model/RiskDevice
     */
    constructor() { 
        
        RiskDevice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RiskDevice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RiskDevice} obj Optional instance to populate.
     * @return {module:model/RiskDevice} The populated <code>RiskDevice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RiskDevice();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * This device's unique identifier
 * @member {String} id
 */
RiskDevice.prototype['id'] = undefined;






export default RiskDevice;

