/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Schema1AddedBy model module.
 * @module model/Schema1AddedBy
 * @version 0.0.1
 */
class Schema1AddedBy {
    /**
     * Constructs a new <code>Schema1AddedBy</code>.
     * @alias module:model/Schema1AddedBy
     */
    constructor() { 
        
        Schema1AddedBy.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Schema1AddedBy</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Schema1AddedBy} obj Optional instance to populate.
     * @return {module:model/Schema1AddedBy} The populated <code>Schema1AddedBy</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Schema1AddedBy();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Schema1AddedBy.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Schema1AddedBy.prototype['name'] = undefined;






export default Schema1AddedBy;

