/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SchemaProvisioning model module.
 * @module model/SchemaProvisioning
 * @version 0.0.1
 */
class SchemaProvisioning {
    /**
     * Constructs a new <code>SchemaProvisioning</code>.
     * @alias module:model/SchemaProvisioning
     */
    constructor() { 
        
        SchemaProvisioning.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SchemaProvisioning</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SchemaProvisioning} obj Optional instance to populate.
     * @return {module:model/SchemaProvisioning} The populated <code>SchemaProvisioning</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SchemaProvisioning();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Indicates if provisioning is enabled for this app.
 * @member {Boolean} enabled
 */
SchemaProvisioning.prototype['enabled'] = undefined;






export default SchemaProvisioning;

