/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetRoleApps200ResponseInner model module.
 * @module model/SetRoleApps200ResponseInner
 * @version 0.0.1
 */
class SetRoleApps200ResponseInner {
    /**
     * Constructs a new <code>SetRoleApps200ResponseInner</code>.
     * @alias module:model/SetRoleApps200ResponseInner
     */
    constructor() { 
        
        SetRoleApps200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetRoleApps200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetRoleApps200ResponseInner} obj Optional instance to populate.
     * @return {module:model/SetRoleApps200ResponseInner} The populated <code>SetRoleApps200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetRoleApps200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Apps unique ID in OneLogin.
 * @member {Number} id
 */
SetRoleApps200ResponseInner.prototype['id'] = undefined;






export default SetRoleApps200ResponseInner;

