/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Status2Status model module.
 * @module model/Status2Status
 * @version 0.0.1
 */
class Status2Status {
    /**
     * Constructs a new <code>Status2Status</code>.
     * @alias module:model/Status2Status
     */
    constructor() { 
        
        Status2Status.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Status2Status</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Status2Status} obj Optional instance to populate.
     * @return {module:model/Status2Status} The populated <code>Status2Status</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Status2Status();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
Status2Status.prototype['type'] = undefined;

/**
 * @member {Number} code
 */
Status2Status.prototype['code'] = undefined;

/**
 * @member {String} message
 */
Status2Status.prototype['message'] = undefined;

/**
 * @member {Boolean} error
 */
Status2Status.prototype['error'] = undefined;






export default Status2Status;

