/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Status1 model module.
 * @module model/Status1
 * @version 0.0.1
 */
class Status1 {
    /**
     * Constructs a new <code>Status1</code>.
     * @alias module:model/Status1
     */
    constructor() { 
        
        Status1.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Status1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Status1} obj Optional instance to populate.
     * @return {module:model/Status1} The populated <code>Status1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Status1();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
Status1.prototype['message'] = undefined;

/**
 * @member {Number} statusCode
 */
Status1.prototype['statusCode'] = undefined;

/**
 * @member {String} name
 */
Status1.prototype['name'] = undefined;






export default Status1;

