/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status2Status from './Status2Status';

/**
 * The Status2 model module.
 * @module model/Status2
 * @version 0.0.1
 */
class Status2 {
    /**
     * Constructs a new <code>Status2</code>.
     * @alias module:model/Status2
     */
    constructor() { 
        
        Status2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Status2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Status2} obj Optional instance to populate.
     * @return {module:model/Status2} The populated <code>Status2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Status2();

            if (data.hasOwnProperty('status')) {
                obj['status'] = Status2Status.constructFromObject(data['status']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Status2Status} status
 */
Status2.prototype['status'] = undefined;






export default Status2;

