/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateClientAppRequest model module.
 * @module model/UpdateClientAppRequest
 * @version 0.0.1
 */
class UpdateClientAppRequest {
    /**
     * Constructs a new <code>UpdateClientAppRequest</code>.
     * @alias module:model/UpdateClientAppRequest
     */
    constructor() { 
        
        UpdateClientAppRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateClientAppRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateClientAppRequest} obj Optional instance to populate.
     * @return {module:model/UpdateClientAppRequest} The populated <code>UpdateClientAppRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateClientAppRequest();

            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} scopes
 */
UpdateClientAppRequest.prototype['scopes'] = undefined;






export default UpdateClientAppRequest;

