/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateAuthorizationServer400Response model module.
 * @module model/UpdateAuthorizationServer400Response
 * @version 0.0.1
 */
class UpdateAuthorizationServer400Response {
    /**
     * Constructs a new <code>UpdateAuthorizationServer400Response</code>.
     * @alias module:model/UpdateAuthorizationServer400Response
     */
    constructor() { 
        
        UpdateAuthorizationServer400Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateAuthorizationServer400Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateAuthorizationServer400Response} obj Optional instance to populate.
     * @return {module:model/UpdateAuthorizationServer400Response} The populated <code>UpdateAuthorizationServer400Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateAuthorizationServer400Response();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('statusCode')) {
                obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} field
 */
UpdateAuthorizationServer400Response.prototype['field'] = undefined;

/**
 * @member {String} message
 */
UpdateAuthorizationServer400Response.prototype['message'] = undefined;

/**
 * @member {Number} statusCode
 */
UpdateAuthorizationServer400Response.prototype['statusCode'] = undefined;

/**
 * @member {String} name
 */
UpdateAuthorizationServer400Response.prototype['name'] = undefined;






export default UpdateAuthorizationServer400Response;

