/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateEnvironmentVariableRequest model module.
 * @module model/UpdateEnvironmentVariableRequest
 * @version 0.0.1
 */
class UpdateEnvironmentVariableRequest {
    /**
     * Constructs a new <code>UpdateEnvironmentVariableRequest</code>.
     * @alias module:model/UpdateEnvironmentVariableRequest
     * @param value {String} The secret value that will be encrypted at rest and injected in applicable hook functions at run time.
     */
    constructor(value) { 
        
        UpdateEnvironmentVariableRequest.initialize(this, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value) { 
        obj['value'] = value;
    }

    /**
     * Constructs a <code>UpdateEnvironmentVariableRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateEnvironmentVariableRequest} obj Optional instance to populate.
     * @return {module:model/UpdateEnvironmentVariableRequest} The populated <code>UpdateEnvironmentVariableRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateEnvironmentVariableRequest();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The secret value that will be encrypted at rest and injected in applicable hook functions at run time.
 * @member {String} value
 */
UpdateEnvironmentVariableRequest.prototype['value'] = undefined;






export default UpdateEnvironmentVariableRequest;

