/**
 * OneLogin API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VerifyFactorVoice200ResponseInner model module.
 * @module model/VerifyFactorVoice200ResponseInner
 * @version 0.0.1
 */
class VerifyFactorVoice200ResponseInner {
    /**
     * Constructs a new <code>VerifyFactorVoice200ResponseInner</code>.
     * @alias module:model/VerifyFactorVoice200ResponseInner
     */
    constructor() { 
        
        VerifyFactorVoice200ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VerifyFactorVoice200ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VerifyFactorVoice200ResponseInner} obj Optional instance to populate.
     * @return {module:model/VerifyFactorVoice200ResponseInner} The populated <code>VerifyFactorVoice200ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerifyFactorVoice200ResponseInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
VerifyFactorVoice200ResponseInner.prototype['id'] = undefined;

/**
 * @member {module:model/VerifyFactorVoice200ResponseInner.StatusEnum} status
 */
VerifyFactorVoice200ResponseInner.prototype['status'] = undefined;

/**
 * @member {String} device_id
 */
VerifyFactorVoice200ResponseInner.prototype['device_id'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
VerifyFactorVoice200ResponseInner['StatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "accepted"
     * @const
     */
    "accepted": "accepted",

    /**
     * value: "rejected"
     * @const
     */
    "rejected": "rejected"
};



export default VerifyFactorVoice200ResponseInner;

